/** Generated by scripts/generate-unreleased.mjs from CHANGELOG.md — do not edit. */
export const UNRELEASED_ITEMS: readonly { text: string; children: string[] }[] = [
  {
    "text": "**Drop a card onto a card to nest it.** The hovered target rings amber — a deliberate contrast with the top/bottom thirds' ordinary insertion line, so a family drop never masquerades as a lane drop — and the drop re-parents the thread under the target; the card menu's Make Top-Level detaches a child again.",
    "children": []
  },
  {
    "text": "**Drag a nested child onto any column floor to top-level it again.** Nested rows drag like cards now, and the floor rings amber for the family detach — dragging the child back onto a card re-nests it, so nest and detach are each other's undo.",
    "children": []
  }
];
