/** Generated by scripts/generate-unreleased.mjs from CHANGELOG.md — do not edit. */
export const UNRELEASED_ITEMS: readonly { text: string; children: string[] }[] = [
  {
    "text": "**The Working lane no longer vanishes when nothing runs.** The Attention board keeps its Working column even when every thread has gone idle; the empty lane reads \"No work in progress\" instead of disappearing.",
    "children": []
  }
];
