/** Generated by scripts/generate-whats-new.mjs from CHANGELOG.md — do not edit. */
export const DERIVED_WHATS_NEW: readonly { version: string; items: readonly string[] }[] = [
  {
    "version": "0.5.21",
    "items": [
      "Escape stops a running thread before closing the pane.",
      "Pinned cards take the pin when they leave the lane.",
      "Columns drained to zero by nesting hide themselves."
    ]
  },
  {
    "version": "0.5.20",
    "items": [
      "Dropping a card into a new column can place it there in the same drag."
    ]
  },
  {
    "version": "0.5.19",
    "items": [
      "Clicking in the pane's chat no longer yanks the transcript back to the bottom."
    ]
  },
  {
    "version": "0.5.18",
    "items": [
      "Answering a question now clears the card from Needs you right away."
    ]
  },
  {
    "version": "0.5.17",
    "items": [
      "Parent lanes now size to fit their cards, and the selected family renders as a wide, readable ruler lane.",
      "Panning releases the lane lock, and at rest the nearest family pins flush into position.",
      "The lane-order toggle moves into the status rail as a vertical picker."
    ]
  },
  {
    "version": "0.5.16",
    "items": [
      "No user-visible board changes."
    ]
  },
  {
    "version": "0.5.15",
    "items": [
      "Dragging a card onto the Pinned lane now pins it."
    ]
  },
  {
    "version": "0.5.14",
    "items": [
      "Full Screen moves into the phone thread pane's actions menu."
    ]
  },
  {
    "version": "0.5.13",
    "items": [
      "Parent thread lanes."
    ]
  },
  {
    "version": "0.5.5",
    "items": [
      "Inline-code workspace paths now verify against the workspace before they become clickable in the board's thread pane."
    ]
  },
  {
    "version": "0.5.4",
    "items": [
      "Recent decisions card in the thread pane."
    ]
  },
  {
    "version": "0.5.3",
    "items": [
      "Backticked workspace paths in thread messages are now clickable in the board's thread pane."
    ]
  },
  {
    "version": "0.5.2",
    "items": [
      "Right-clicking a nested child thread opened the parent card's menu on top of the child's."
    ]
  },
  {
    "version": "0.5.1",
    "items": [
      "The Done column now sorts by when each thread was marked done, newest first, instead of by the board's newest-activity order."
    ]
  },
  {
    "version": "0.5.0",
    "items": [
      "The open pane now lives in the panel's URL, so bb's back arrow restores it.",
      "What's new: a gift button in the toolbar lists recent changes after an update.",
      "The screenshot harness no longer render-loops."
    ]
  },
  {
    "version": "0.4.6",
    "items": [
      "Click an empty area of the board to close the thread pane."
    ]
  },
  {
    "version": "0.4.5",
    "items": [
      "The first drag-and-drop reorder in a column silently did nothing unless the drop landed at the very top."
    ]
  },
  {
    "version": "0.4.4",
    "items": [
      "Thread mention links in pane messages were swallowed."
    ]
  },
  {
    "version": "0.4.3",
    "items": [
      "Relative file links in pane messages no longer open as broken browser URLs."
    ]
  },
  {
    "version": "0.4.2",
    "items": [
      "Rank refusal banners could not be dismissed."
    ]
  },
  {
    "version": "0.4.1",
    "items": [
      "Selected option indicators were invisible in the pane question form."
    ]
  },
  {
    "version": "0.4.0",
    "items": [
      "Per-column card rank ordering.",
      "The pane question form reaches parity with the host's shipped QuestionForm.",
      "The board's cards and lanes carry drag-testability attributes.",
      "The screenshot harness simulates a third unread thread.",
      "Screenshot runs stop failing two runs in three."
    ]
  },
  {
    "version": "0.3.5",
    "items": [
      "The selected card stays in view when the thread pane opens."
    ]
  },
  {
    "version": "0.3.4",
    "items": [
      "Agent questions are answerable from the thread pane."
    ]
  },
  {
    "version": "0.3.3",
    "items": [
      "New threads inherit the single selected project filter."
    ]
  },
  {
    "version": "0.3.2",
    "items": [
      "Long filter dropdowns gain a search bar."
    ]
  },
  {
    "version": "0.3.1",
    "items": [
      "The plugin is renamed to Focus Board."
    ]
  },
  {
    "version": "0.3.0",
    "items": [
      "The new `bb thread-board` CLI manages the plugin's own state."
    ]
  },
  {
    "version": "0.2.0",
    "items": [
      "Done state moves to per-thread plugin metadata, server-side and surviving across devices and reloads.",
      "The sweep arms with a first click and performs with a second: arm-then-confirm buttons sit on the Done and Awhile-ago columns.",
      "Ticket chips render and link out from titles and branches.",
      "GitHub status dots appear on matching chips.",
      "Threads spawned as children nest under their parent card as collapsible rows, Jira-subissue style.",
      "Child rows gain full titles, and archived children stay nested.",
      "`done_list` returns richer Done records.",
      "The `done-changed` realtime payload narrows to the thread.",
      "The README's \"makes no server-side writes\" wording is corrected."
    ]
  }
];
