/** Generated by scripts/generate-whats-new.mjs from CHANGELOG.md — do not edit. */
export const DERIVED_WHATS_NEW: readonly { version: string; items: readonly string[] }[] = [
  {
    "version": "0.5.21",
    "items": [
      "Escape stops a running thread before closing the pane.",
      "Pinned cards take the pin when they leave the lane.",
      "Columns drained to zero by nesting hide themselves."
    ]
  },
  {
    "version": "0.5.20",
    "items": [
      "Dropping a card into a new column can place it there in the same drag."
    ]
  },
  {
    "version": "0.5.19",
    "items": [
      "Clicking in the pane's chat no longer yanks the transcript back to the bottom."
    ]
  },
  {
    "version": "0.5.18",
    "items": [
      "Answering a question now clears the card from Needs you right away."
    ]
  },
  {
    "version": "0.5.17",
    "items": [
      "Parent-thread view: family lanes size to their content; the locked ruler lane renders large readable cards while context lanes wrap compact cards capped by the viewport width.",
      "Panning horizontally releases the ruler lock; at rest the nearest family pins flush into position before a single re-cut, clicked subtasks stay visible through the motion, and the board settles quiet (regression-tested with a real wheel-event pan in the UAT suite).",
      "The lane-order toggle is a vertical picker in the status rail; viewport resizes while a lane is locked keep the ruler and band alignment; clicking a lane header during an in-flight glide wins the lock over the pan's target."
    ]
  },
  {
    "version": "0.5.16",
    "items": [
      "No user-visible board changes; the What's-new modal restates the 0.5.15 notes."
    ]
  },
  {
    "version": "0.5.15",
    "items": [
      "Dragging a card onto the Pinned lane now pins it."
    ]
  },
  {
    "version": "0.5.14",
    "items": [
      "Full Screen moves into the phone thread pane's actions menu."
    ]
  },
  {
    "version": "0.5.13",
    "items": [
      "Parent thread lanes."
    ]
  },
  {
    "version": "0.5.5",
    "items": [
      "Inline-code workspace paths now verify against the workspace before they become clickable in the board's thread pane."
    ]
  },
  {
    "version": "0.5.4",
    "items": [
      "Recent decisions card in the thread pane."
    ]
  },
  {
    "version": "0.5.3",
    "items": [
      "Backticked workspace paths in thread messages are now clickable in the board's thread pane."
    ]
  },
  {
    "version": "0.5.2",
    "items": [
      "Right-clicking a nested child thread opened the parent card's menu on top of the child's."
    ]
  },
  {
    "version": "0.5.1",
    "items": [
      "The Done column now sorts by when each thread was marked done, newest first, instead of by the board's newest-activity order."
    ]
  },
  {
    "version": "0.5.0",
    "items": [
      "The open pane now lives in the panel's URL, so bb's back arrow restores it.",
      "What's new: a gift button in the toolbar lists recent changes after an update.",
      "The screenshot harness no longer render-loops."
    ]
  },
  {
    "version": "0.4.6",
    "items": [
      "Click an empty area of the board to close the thread pane."
    ]
  },
  {
    "version": "0.4.5",
    "items": [
      "The first drag-and-drop reorder in a column silently did nothing unless the drop landed at the very top."
    ]
  },
  {
    "version": "0.4.4",
    "items": [
      "Thread mention links in pane messages were swallowed."
    ]
  },
  {
    "version": "0.4.3",
    "items": [
      "Relative file links in pane messages no longer open as broken browser URLs."
    ]
  },
  {
    "version": "0.4.2",
    "items": [
      "Rank refusal banners could not be dismissed."
    ]
  },
  {
    "version": "0.4.1",
    "items": [
      "Selected option indicators in the pane question form were invisible: the check rendered in `primary-foreground` on a transparent border, and this theme's `primary` is not a strong fill, so picking an answer looked like nothing happened."
    ]
  },
  {
    "version": "0.4.0",
    "items": [
      "Per-column card rank ordering.",
      "Pane question form: parity with the host's QuestionForm: the pending question card now mirrors the host's shipped form rather than a stacked long form.",
      "The board marks each lane and each card with `data-column-id`, `data-column-ordered`, and `data-rank-slot` attributes, which the UAT harness reads to drive real drag gestures.",
      "The simulated board in the screenshot harness gained a third unread thread and an in-memory rank store, and the screenshots are regenerated to match.",
      "`scripts/screenshot/shoot.mjs` failed roughly two runs in three with `TargetCloseError` on `Emulation.setTouchEmulationEnabled`."
    ]
  },
  {
    "version": "0.3.5",
    "items": [
      "Keep the selected card in view when the thread pane opens: the pane squeezes the board, which could leave the open thread's card clipped off to the right."
    ]
  },
  {
    "version": "0.3.4",
    "items": [
      "Answer agent questions from the thread pane: the pane now renders a pending question as a real form and submits the answer from the board — the host's embedded chat only shows these in the main thread view, so the question tool used to block until timeout while the pane showed nothing."
    ]
  },
  {
    "version": "0.3.3",
    "items": [
      "New threads inherit a single-project filter: when exactly one project is selected in the filter, the toolbar's new thread button and the board's new task affordance create the thread in that project."
    ]
  },
  {
    "version": "0.3.2",
    "items": [
      "Search bar in long filter dropdowns: the toolbar's Project and Provider dropdowns (and any other option list past five rows) now open with a search field, matching the model picker's affordance."
    ]
  },
  {
    "version": "0.3.1",
    "items": [
      "Renamed to Focus Board: package `bb-plugin-focus-board`, plugin ID `focus-board`, CLI `bb focus-board`, and `focus-board:` preference keys."
    ]
  },
  {
    "version": "0.3.0",
    "items": [
      "`bb thread-board` CLI: one subcommand managing the plugin's own state — a third surface over the same Done/metadata store, never a re-spelling of `bb thread`: - `bb thread-board done list|mark|clear` — list done threads (with `doneAt`, `keep`, and a `not in the live thread list` flag; orphaned marks on deleted threads survive via a `done-index` KV), stamp Done (idempotent, refreshes `doneAt`), clear it."
    ]
  },
  {
    "version": "0.2.0",
    "items": [
      "Done state moves to plugin metadata: Done is per-thread bb-native plugin metadata in the board's own namespace (`done` → `{ doneAt, keep?",
      "Sweep: two-click arm-then-confirm buttons per column — Done and Awhile-ago.",
      "Ticket chips: `PROJ-123`, `#1284`, and GitHub issue/PR URLs in titles and branches render as chips that link out; inert when the project has no GitHub remote.",
      "GitHub status dots: the server reads the official GitHub plugin's local cache read-only and puts open/closed/merged dots on matching chips; a missing cache degrades to chip-only rendering — the board never breaks.",
      "Parent-child nesting: threads spawned as children render as collapsible rows under their parent card (Jira-subissue style), with a needs-you child promoted to its own column so it is never buried, a 2-level depth cap with `+N more` chip, family-aware filtering, and a defensive family index (orphans → roots, cycles unlinked).",
      "Nesting refinements: child rows carry the full title (up to two lines); archived children stay nested under their live parent, dimmed with an archived mark; a \"Nest child threads\" toolbar toggle flattens the board to independent cards (nesting off = fully flat, filters per-thread).",
      "`done_list` returns `{ doneIds, records }` where records carry the ISO-8601 `doneAt` stamp and `keep` flag the sweep and (future) CLI consume.",
      "`done-changed` realtime payload is `{ threadId, done }` (was `{ count }`); keep-flag writes publish the same signal.",
      "README's \"makes no server-side writes\" wording corrected to describe what the board actually owns (pin state, read state, Done — never thread content)."
    ]
  }
];
