/** Generated by scripts/generate-whats-new.mjs from CHANGELOG.md — do not edit. */
export const DERIVED_WHATS_NEW: readonly { version: string; items: readonly { lead: string; children: readonly string[] }[] }[] = [
  {
    "version": "1.1.0",
    "items": [
      {
        "lead": "The pane's question form keeps half-answered questions alive.",
        "children": []
      },
      {
        "lead": "Card menus now surface a thread's controlled browser tab.",
        "children": []
      },
      {
        "lead": "Board cards carry linked-issue chips.",
        "children": [
          "Agents are nudged to link."
        ]
      },
      {
        "lead": "Board links reach any tracker.",
        "children": []
      },
      {
        "lead": "The pane's actions menu now leads with the state toggles.",
        "children": []
      },
      {
        "lead": "Ticket chips say their source and their kind at a glance.",
        "children": []
      },
      {
        "lead": "The selected parent's lane stays inside the viewport.",
        "children": []
      },
      {
        "lead": "The board no longer silently vanishes when a checkout's node_modules goes bad.",
        "children": []
      },
      {
        "lead": "Word-shaped ticket keys no longer chip.",
        "children": []
      },
      {
        "lead": "Mobile thread pane: thread actions drop from a split caret, like Open in.",
        "children": []
      }
    ]
  },
  {
    "version": "1.0.0",
    "items": [
      {
        "lead": "Toolbar search reaches project names and branches.",
        "children": []
      },
      {
        "lead": "✨ \"The thread's active model\" no longer lands on a metered catalog default.",
        "children": []
      },
      {
        "lead": "Reordering from two boards at once can no longer drop a column's order.",
        "children": []
      },
      {
        "lead": "A corrupt snooze record can no longer silence the other wake-ups.",
        "children": []
      },
      {
        "lead": "An absurd snooze duration refuses cleanly.",
        "children": []
      },
      {
        "lead": "A drop on a column title never writes an order.",
        "children": []
      },
      {
        "lead": "The Working lane no longer vanishes when nothing runs.",
        "children": []
      }
    ]
  },
  {
    "version": "0.9.0",
    "items": [
      {
        "lead": "✨ auto-rename gains the thread's own model as a fallback.",
        "children": [
          "Titles come from the thread's true originating prompt."
        ]
      },
      {
        "lead": "Sweep selection takes shift-click and ⌘/Ctrl-click.",
        "children": []
      },
      {
        "lead": "Open menu in the thread pane header.",
        "children": [
          "Full screen joins the dropdown."
        ]
      },
      {
        "lead": "The Done column sorts by activity recency again, most recently active on top.",
        "children": []
      },
      {
        "lead": "A double-tap of Escape no longer closes the thread pane.",
        "children": []
      },
      {
        "lead": "Family cards fold their child rows into a \"N child threads\" line with a strip of status-colored dots immediately below it.",
        "children": []
      },
      {
        "lead": "✨ \"New child thread…\" opens a composer preset to the parent.",
        "children": [
          "The child starts where the parent runs."
        ]
      },
      {
        "lead": "Drop a card onto a card to nest it.",
        "children": [
          "Drag a nested child onto any column header or floor to top-level it again."
        ]
      },
      {
        "lead": "Mark Unread joins the pane's actions as one attached split control.",
        "children": []
      }
    ]
  },
  {
    "version": "0.8.0",
    "items": [
      {
        "lead": "Collapsible nested children on family cards.",
        "children": []
      },
      {
        "lead": "Snooze: read now, unread again at a target time.",
        "children": []
      },
      {
        "lead": "✨ auto-rename in the pane's title editor.",
        "children": []
      },
      {
        "lead": "The thread pane's actions menu pins again.",
        "children": []
      },
      {
        "lead": "Every lane now has its sweep, each with its own destination.",
        "children": [
          "The sweep pill drops the word \"Sweep.\" Screen-reader labels keep the full sweep wording."
        ]
      }
    ]
  },
  {
    "version": "0.7.0",
    "items": [
      {
        "lead": "New threads compose inside the board.",
        "children": []
      }
    ]
  },
  {
    "version": "0.6.0",
    "items": [
      {
        "lead": "A family's done work renders as a projection card in the Done column.",
        "children": [
          "Big families scroll inside their card."
        ]
      },
      {
        "lead": "Filter dropdowns with a search bar gain a select-all checkbox.",
        "children": [
          "Enter applies a sole dropdown search match."
        ]
      },
      {
        "lead": "Developer toggle: pane chat scroll instrumentation.",
        "children": []
      },
      {
        "lead": "The brand icon is restored as the lane-and-card mark.",
        "children": [
          "The sidebar row and pane title bar draw the mark too."
        ]
      },
      {
        "lead": "The sweep is rebuilt around choosing exactly what gets archived, and idle threads resurface instead of vanishing.",
        "children": [
          "Sweep mode is manual: enter it any time and click the cards to archive."
        ]
      },
      {
        "lead": "Pinned cards carry their thread's state both ways: read state and needs-you.",
        "children": [
          "Marking a card unread now returns a parked card to Pinned from any surface."
        ]
      },
      {
        "lead": "The thread pane's project/branch footer line is gone.",
        "children": []
      },
      {
        "lead": "Menu moves bring the destination lane into view.",
        "children": []
      },
      {
        "lead": "Clicking in the pane's chat no longer yanks the transcript to the newest message while you are scrolled up.",
        "children": []
      }
    ]
  },
  {
    "version": "0.5.21",
    "items": [
      {
        "lead": "Escape stops a running thread before closing the pane.",
        "children": []
      },
      {
        "lead": "Pinned cards take the pin when they leave the lane.",
        "children": []
      },
      {
        "lead": "Columns drained to zero by nesting hide themselves.",
        "children": []
      }
    ]
  },
  {
    "version": "0.5.20",
    "items": [
      {
        "lead": "Dropping a card into a new column can place it there in the same drag.",
        "children": []
      }
    ]
  },
  {
    "version": "0.5.19",
    "items": [
      {
        "lead": "Clicking in the pane's chat no longer yanks the transcript back to the bottom.",
        "children": []
      }
    ]
  },
  {
    "version": "0.5.18",
    "items": [
      {
        "lead": "Answering a question now clears the card from Needs you right away.",
        "children": []
      }
    ]
  },
  {
    "version": "0.5.17",
    "items": [
      {
        "lead": "Parent lanes now size to fit their cards.",
        "children": []
      },
      {
        "lead": "Panning releases the lane lock, and at rest the nearest family pins flush into position.",
        "children": []
      },
      {
        "lead": "The lane-order toggle moves into the status rail as a vertical picker.",
        "children": []
      }
    ]
  },
  {
    "version": "0.5.16",
    "items": [
      {
        "lead": "No user-visible board changes.",
        "children": []
      }
    ]
  },
  {
    "version": "0.5.15",
    "items": [
      {
        "lead": "Dragging a card onto the Pinned lane now pins it.",
        "children": []
      }
    ]
  },
  {
    "version": "0.5.14",
    "items": [
      {
        "lead": "Full Screen moves into the phone thread pane's actions menu.",
        "children": []
      }
    ]
  },
  {
    "version": "0.5.13",
    "items": [
      {
        "lead": "Parent thread lanes.",
        "children": []
      }
    ]
  },
  {
    "version": "0.5.5",
    "items": [
      {
        "lead": "Inline-code workspace paths now verify against the workspace before they become clickable.",
        "children": []
      }
    ]
  },
  {
    "version": "0.5.4",
    "items": [
      {
        "lead": "Recent decisions card in the thread pane.",
        "children": []
      }
    ]
  },
  {
    "version": "0.5.3",
    "items": [
      {
        "lead": "Backticked workspace paths in thread messages are now clickable in the board's pane.",
        "children": []
      }
    ]
  },
  {
    "version": "0.5.2",
    "items": [
      {
        "lead": "Right-clicking a nested child thread no longer stacks the parent card's menu on top of the child's.",
        "children": []
      }
    ]
  },
  {
    "version": "0.5.1",
    "items": [
      {
        "lead": "The Done column sorts by when each thread was marked done, newest first.",
        "children": []
      }
    ]
  },
  {
    "version": "0.5.0",
    "items": [
      {
        "lead": "The open pane now lives in the panel's URL, so bb's back arrow restores it.",
        "children": []
      },
      {
        "lead": "What's new: a gift button in the toolbar lists recent changes after an update, pulsing until opened.",
        "children": []
      },
      {
        "lead": "The screenshot harness no longer render-loops.",
        "children": []
      }
    ]
  },
  {
    "version": "0.4.6",
    "items": [
      {
        "lead": "Click an empty area of the board to close the thread pane.",
        "children": []
      }
    ]
  },
  {
    "version": "0.4.5",
    "items": [
      {
        "lead": "The first drag-and-drop reorder in a column silently did nothing unless the drop landed at the top.",
        "children": []
      }
    ]
  },
  {
    "version": "0.4.4",
    "items": [
      {
        "lead": "Thread mention links in pane messages were swallowed.",
        "children": []
      }
    ]
  },
  {
    "version": "0.4.3",
    "items": [
      {
        "lead": "Relative file links in pane messages no longer open as broken browser URLs.",
        "children": []
      }
    ]
  },
  {
    "version": "0.4.2",
    "items": [
      {
        "lead": "Rank refusal banners can be dismissed.",
        "children": []
      }
    ]
  },
  {
    "version": "0.4.1",
    "items": [
      {
        "lead": "Selected option indicators are visible in the pane question form.",
        "children": []
      }
    ]
  },
  {
    "version": "0.4.0",
    "items": [
      {
        "lead": "Per-column card rank ordering.",
        "children": [
          "Orders are stored per column, so a card that leaves and comes back returns to the slot it left."
        ]
      },
      {
        "lead": "The pane question form reaches parity with the host's shipped QuestionForm.",
        "children": []
      },
      {
        "lead": "The board's cards and lanes carry drag-testability attributes.",
        "children": []
      },
      {
        "lead": "The screenshot harness simulates a third unread thread.",
        "children": []
      },
      {
        "lead": "Screenshot runs stop failing two runs in three.",
        "children": []
      }
    ]
  },
  {
    "version": "0.3.5",
    "items": [
      {
        "lead": "The selected card stays in view when the thread pane opens.",
        "children": []
      }
    ]
  },
  {
    "version": "0.3.4",
    "items": [
      {
        "lead": "Agent questions are answerable from the thread pane.",
        "children": []
      }
    ]
  },
  {
    "version": "0.3.3",
    "items": [
      {
        "lead": "New threads inherit the single selected project filter.",
        "children": []
      }
    ]
  },
  {
    "version": "0.3.2",
    "items": [
      {
        "lead": "Long filter dropdowns gain a search bar.",
        "children": []
      }
    ]
  },
  {
    "version": "0.3.1",
    "items": [
      {
        "lead": "The plugin is renamed to Focus Board.",
        "children": []
      }
    ]
  },
  {
    "version": "0.3.0",
    "items": [
      {
        "lead": "The new `bb thread-board` CLI manages the plugin's own state.",
        "children": [
          "`done list|mark|clear` — agents get free Done marking."
        ]
      }
    ]
  },
  {
    "version": "0.2.0",
    "items": [
      {
        "lead": "Done state moves to per-thread plugin metadata, server-side and surviving across devices and reloads.",
        "children": []
      },
      {
        "lead": "The sweep arms with a first click and performs with a second, on the Done and Awhile-ago columns.",
        "children": []
      },
      {
        "lead": "Ticket chips render and link out from titles and branches.",
        "children": []
      },
      {
        "lead": "GitHub status dots appear on matching chips, read from the official GitHub plugin's local cache.",
        "children": []
      },
      {
        "lead": "Threads spawned as children nest under their parent card, Jira-subissue style.",
        "children": []
      },
      {
        "lead": "Child rows gain full titles, and archived children stay nested.",
        "children": []
      },
      {
        "lead": "`done_list` returns richer Done records: `{ doneIds, records }` with the ISO `doneAt` stamp and `keep` flag.",
        "children": []
      },
      {
        "lead": "The `done-changed` realtime payload narrows to the thread: `{ threadId, done }`, was `{ count }`.",
        "children": []
      },
      {
        "lead": "The README's \"makes no server-side writes\" wording is corrected.",
        "children": []
      }
    ]
  }
];
